app:
  name: "gin-basic-scaffold"
  mode: "dev"
  port: 8888
  version: "0.1.0"
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200 # 最大文件大小 MB
  max_age: 30 # 最大保存天数
  max_backups: 7 # 最大文件数
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  db_name: "gin-basic-scaffold"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100
