basePath: /api/v1
definitions:
  models.CommonResponse:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
host: 127.0.0.1:8088
info:
  contact:
    email: support@swagger.io
    name: Liuzhen
    url: http://www.swagger.io/support
  description: gin-bluebell 基于Gin框架的Web通用脚手架模板
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/license-2.0.html
  termsOfService: http://swagger.io/terms/
  title: gin-bluebell api docs
  version: 0.1.0
paths:
  /signup:
    post:
      consumes:
      - application/json
      description: 处理注册请求
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - in: query
        name: password
        required: true
        type: string
      - in: query
        name: re_password
        required: true
        type: string
      - in: query
        name: username
        required: true
        type: string
      produces:
      - appliction/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CommonResponse'
      security:
      - ApiKeyAuth: []
      summary: 处理注册请求
      tags:
      - 用户相关
swagger: "2.0"
